1257620 update company document upload client
kmdlogic/kmd-logic-citizen-documents-client pull request #36
Opened 2022-04-21 07:02 UTC by deviprasadkotian

Updated client for company document upload client

2022-04-21 09:28 UTC, Araballi approved these changes
LGTM

2022-04-22 10:42 UTC, Araballi requested changes
version change

2022-04-25 05:16 UTC, NakulSeerpu commented
Pls increment the number in directoru.build.props and also update  changes.md

2022-04-28 07:26 UTC, Araballi commented on Directory.Build.props
> +		<VersionPrefix Condition=" '$(VersionPrefix)' == '' ">3.0.2</VersionPrefix>
Asked to change 3.1.0

2022-05-10 05:10 UTC, Araballi approved these changes

2022-05-10 05:28 UTC, merged